# Generated by Django 5.0.7 on 2024-09-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mynotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('option', models.CharField(max_length=100)),
                ('myfile', models.FileField(upload_to='MyNotes')),
                ('desc', models.TextField()),
            ],
        ),
    ]
